package(default_visibility = ["//src/main/scala/grayson/yggdrasil:__subpackages__"])

scala_library(
    name = "prelude",
    srcs = glob([
        "*.scala",
    ]),
    deps = [
    	 "@maven//:org_typelevel_cats_core_2_12",
	 "@maven//:org_typelevel_cats_effect_2_12",
    ],
)